services:
  botpress:
    image: botpress/server:latest
    ports:
      - "10000:10000"  # غيّر المنفذ هنا
    environment:
      - BP_HOST=0.0.0.0
      - BP_PORT=10000
      - DATABASE_URL=${DATABASE_URL}
      - BP_EXTERNAL_URL=${BP_EXTERNAL_URL}
      - BP_JWT_SECRET=${BP_JWT_SECRET}