version: '3'
services:
  botpress:
    image: botpress/server:latest
    ports:
      - "3000:3000"
    environment:
      - BP_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}  # سيتم تعبئتها من ملف .env
    # احذف قسم depends_on إذا كنت تستخدم قاعدة بيانات خارجية (Neon.tech)